### ISSUE TITLE
Mods update checker link leads to nowhere and throws an error.

### ISSUE THREAD

**Issue by ProxyNeko** [psych-ward/Sisser#1]
The link in your mods.toml file for update checks is not valid so throws a warning in console/logs (Server returned error 400), you can either comment it out with a # at the start of that line or have it point to a file on github to check for updates :)

[The line I'm referring to is here](https://github.com/psych-ward/Sisser/blob/master/src/main/resources/META-INF/mods.toml#L21)

**Comment by DanteChaos** [comment]
Thanks for letting me know, i shall fix it in the coming weekend. And sorry for the late reaction

**Comment by DanteChaos** [comment]
Well aint the weekend but pushed a new version with the checked commented for now. I will fix the link so it will look for proper update once i got the MC 15 version done
